# Generated by Django 4.2.7 on 2025-10-10 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Recommendation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "recommendation_type",
                    models.CharField(
                        choices=[
                            ("stock", "Stock Management"),
                            ("marketing", "Marketing"),
                            ("quality", "Quality Control"),
                            ("trending", "Trending Analysis"),
                            ("customer", "Customer Insights"),
                            ("revenue", "Revenue Optimization"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("urgent", "Urgent"),
                        ],
                        default="medium",
                        max_length=10,
                    ),
                ),
                ("action_required", models.BooleanField(default=True)),
                (
                    "action_text",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "data_points",
                    models.JSONField(
                        default=dict, help_text="Supporting data for the recommendation"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "analytics_recommendations",
                "ordering": ["-priority", "-created_at"],
            },
        ),
    ]
