# Generated by Django 4.2.7 on 2025-10-19 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Recommendation",
        ),
    ]
