# Generated by Django 4.2.7 on 2025-09-26 06:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feedback", "0004_add_default_values"),
    ]

    operations = [
        migrations.AddField(
            model_name="feedback",
            name="is_featured",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="feedback",
            name="is_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="message",
            field=models.TextField(
                help_text="Please provide detailed feedback (10-1000 characters)",
                validators=[
                    django.core.validators.MinLengthValidator(
                        10,
                        message="Feedback message must be at least 10 characters long.",
                    ),
                    django.core.validators.MaxLengthValidator(
                        1000, message="Feedback message cannot exceed 1000 characters."
                    ),
                ],
            ),
        ),
    ]
