# Generated by Django 4.2.7 on 2025-10-09 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feedback", "0005_feedback_is_featured_feedback_is_verified_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="feedback",
            name="cake_image",
            field=models.ImageField(
                blank=True,
                help_text="Upload an image of the delivered cake",
                null=True,
                upload_to="feedback_images/",
            ),
        ),
        migrations.AddField(
            model_name="feedback",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
