# Generated by Django 4.2.7 on 2025-10-09 15:00

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("orders", "0006_auto_20250920_2105"),
        ("feedback", "0006_feedback_cake_image_feedback_updated_at"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="feedback",
            unique_together={("user", "order")},
        ),
    ]
