# Generated by Django 4.2.7 on 2025-10-11 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("feedback", "0007_alter_feedback_unique_together"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="feedback",
            unique_together=set(),
        ),
    ]
