# Generated by Django 4.2.7 on 2025-09-16 14:54

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cakes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cake', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='cakes.cake')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cake_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'cake_reviews',
                'unique_together': {('cake', 'user')},
            },
        ),
    ]
