# Generated by Django 4.2.7 on 2025-09-25 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cakes', '0002_review'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='review',
            unique_together=set(),
        ),
    ]
