# Generated by Django 4.2.7 on 2025-10-19 09:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("orders", "0007_order_guest_email_order_guest_phone_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeletedOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("original_order_id", models.IntegerField()),
                ("order_number", models.CharField(max_length=20)),
                ("customer_id", models.IntegerField(blank=True, null=True)),
                (
                    "customer_username",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                (
                    "customer_email",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                ("order_status", models.CharField(max_length=20)),
                ("payment_status", models.CharField(max_length=20)),
                ("payment_method", models.CharField(max_length=10)),
                ("order_type", models.CharField(max_length=10)),
                ("subtotal", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "tax",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "delivery_fee",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("total_amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("order_items", models.JSONField(default=list)),
                (
                    "shipping_address",
                    models.JSONField(blank=True, default=dict, null=True),
                ),
                ("original_created_at", models.DateTimeField()),
                ("original_updated_at", models.DateTimeField()),
                ("deleted_at", models.DateTimeField(auto_now_add=True)),
                ("deletion_reason", models.TextField(blank=True, null=True)),
                ("is_restored", models.BooleanField(default=False)),
                ("restored_at", models.DateTimeField(blank=True, null=True)),
                ("restored_order_id", models.IntegerField(blank=True, null=True)),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="deleted_orders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "restored_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="restored_orders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "deleted_orders",
                "ordering": ["-deleted_at"],
            },
        ),
    ]
