# Generated by Django 4.2.7 on 2025-10-20 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0008_deletedorder"),
    ]

    operations = [
        migrations.DeleteModel(
            name="DeletedOrder",
        ),
    ]
